apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
data:
  MONGODB_USER: 'YWRtaW4=' # admin in base64
  MONGODB_PASSWORD: 'cGFzc3dvcmQxMjM=' # password123 in base64
