apiVersion: v1
kind: Service
metadata:
  name: grade-submission-portal
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: grade-submission-portal
  ports:
    - port: 5001 # service port (internal access)
      targetPort: 5001 # pod port where app listens
      nodePort: 32000 # external port on the node (30000-32000)
