apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-portal
  namespace: grade-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: grade-submission-portal

    # Runtime Requirements
    spec:
      containers:
        # Container 1
        - name: grade-submission-portal
          image: rslim087/kubernetes-course-grade-submission-portal
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 30 # wait for app to start before probing
            periodSeconds: 5 # probe every 5s after initial delay
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5001
            periodSeconds: 5 # probe every 5s
          env:
            - name: GRADE_SERVICE_HOST
              value: grade-submission-api # resolves to the ClusterIP service - value is name of service.
          resources:
            requests:
              memory: '128Mi'
              cpu: '200m'
            limits:
              memory: '128Mi'
          ports:
            - containerPort: 5001
